Update ramdisk

diff --git a/linux/ramdisk b/linux/ramdisk
--- a/linux/ramdisk
+++ b/linux/ramdisk
@@ -6,7 +6,15 @@ version="2023.10.27-1308"
 path="/mnt/ramdisk"
 size="8G"
 
-function create_ramdisk() {
+function show_usage() {
+    echo "Usage: $script_name [install|uninstall]"
+    echo "Commands:"
+    echo "  install                        Install RAM disk"
+    echo "  uninstall                      Uninstall RAM disk"
+    exit 1
+}
+
+function install_ramdisk() {
     # 사용자로부터 경로와 용량 입력 받기
     read -p "Ramdisk를 설치할 위치를 입력하세요 (기본값: $path): " custom_path
     path=${custom_path:-$path}
@@ -48,7 +56,7 @@ function create_ramdisk() {
     echo "램디스크 설치완료!! 시작시 자동실행합니다."
 }
 
-function delete_ramdisk() {
+function uninstall_ramdisk() {
 
     local disks=( $(df -h | grep '^tmpfs' | grep -v '/run\|/dev\|/sys' | awk '{print $6}') )
     local count=${#disks[@]}
@@ -78,30 +86,19 @@ function delete_ramdisk() {
     fi
 }
 
-if [ "$1" == "setup" ]; then
-    while true; do
-        echo "$script_name v$version"
-        echo ""
-        echo "# Select an option:"
-        echo "    1) Create ramdisk"
-        echo "    2) Delete ramdisk"
-        echo "    q) Quit"
-        echo ""
-        read -p "Enter your choice: " choice
-    
-        case $choice in
-            1) create_ramdisk;;
-            2) delete_ramdisk;;
-            q) exit 0;;
-            *) echo "Invalid choice. Please try again.";;
-        esac
-    done
-elif [ "$1" == "help" ]; then
+while true; do
+    echo "Version: $version"
+    echo ""
+    echo "  1) Install"
+    echo "  2) Uninstall"
+    echo "  q) Quit"
+    echo ""
+    read -p "# Enter your choice: " choice
 
-    echo "Usage: ./$script_name [option]"
-    echo "Options:"
-    echo "  setup  Show menu to create or delete ramdisk"
-    echo "  help   Show usage instructions"
-else
-    echo "Invalid option. Use './ramdisk.sh help' for usage instructions."
-fi
+    case $choice in
+        1) install_ramdisk;;
+        2) uninstall_ramdisk;;
+        q) exit 0;;
+        *) echo "Invalid choice. Please try again.";;
+    esac
+done
